# Font style metadata
name = "my_font"

# Optional Google font URL
google_fonts = "family=Newsreader"

# Font families
heading_font = "Montserrat"
body_font = "Newsreader"
nav_font = "Roboto"
mono_font = "Roboto Mono"